FROM python:3.12-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        docker.io \
        ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

CMD ["python", "-m", "pytest"]
